/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { OrbitControls, Stage, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
export function Cupcake2({
  flavor,
  isCreamFilling = true,
  IscherryPearl = true,
  ...props
}) {
  const { nodes, materials } = useGLTF("/cupcake2.gltf");
  const ref = useRef();
  useFrame((state, delta) => (ref.current.rotation.y += delta * 0.2));

  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0, 0.567, 0]} scale={[0.804, 1, 0.804]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.envase}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials.lineEnvase}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chocolate.geometry}
        material={materials[flavor]}
        position={[0, 1.397, 0]}
        scale={[1.298, 0.869, 1.298]}
      />
      {isCreamFilling && (
        <>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.crema.geometry}
            material={materials.crema}
            position={[0, 2.244, 0]}
            scale={[1.022, 2.42, 1.022]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas.geometry}
              material={materials.chispas}
              position={[0.535, -0.242, 0.471]}
              rotation={[-1.808, -0.019, -3.073]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_1.geometry}
              material={materials.chispas}
              position={[0.737, -0.243, -0.104]}
              rotation={[-1.554, -0.074, -1.781]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_2.geometry}
              material={materials.chispas}
              position={[0.562, -0.245, -0.233]}
              rotation={[-1.535, -0.037, -0.612]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_3.geometry}
              material={materials.chispas}
              position={[0.485, -0.24, -0.411]}
              rotation={[-1.638, -0.372, -1.597]}
              scale={[0.013, 0.023, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_4.geometry}
              material={materials.chispas}
              position={[0.504, -0.241, -0.334]}
              rotation={[-1.552, -0.138, -1.143]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_5.geometry}
              material={materials.chispas}
              position={[0.265, -0.233, -0.625]}
              rotation={[-1.213, 0.135, 0.317]}
              scale={[0.018, 0.031, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_6.geometry}
              material={materials.chispas}
              position={[0.229, -0.244, -0.567]}
              rotation={[-1.514, 0.013, 0.179]}
              scale={[0.013, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_7.geometry}
              material={materials.chispas}
              position={[0.367, -0.245, -0.586]}
              rotation={[-1.532, 0.007, 0.146]}
              scale={[0.014, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_8.geometry}
              material={materials.chispas}
              position={[-0.076, -0.241, -0.742]}
              rotation={[-1.218, -0.335, -0.707]}
              scale={[0.014, 0.023, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_9.geometry}
              material={materials.chispas}
              position={[-0.325, -0.246, -0.463]}
              rotation={[-1.537, 0.016, 0.323]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_10.geometry}
              material={materials.chispas}
              position={[-0.652, -0.236, -0.378]}
              rotation={[-1.522, 0.216, 1.654]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_11.geometry}
              material={materials.chispas}
              position={[-0.572, -0.245, -0.276]}
              rotation={[-1.558, 0.057, 1.798]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_12.geometry}
              material={materials.chispas}
              position={[-0.563, -0.244, 0.239]}
              rotation={[-1.612, 0.043, 2.52]}
              scale={[0.015, 0.027, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_13.geometry}
              material={materials.chispas}
              position={[-0.755, -0.241, 0.135]}
              rotation={[-1.548, 0.102, 1.757]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_14.geometry}
              material={materials.chispas}
              position={[-0.739, -0.243, 0.14]}
              rotation={[-1.583, 0.064, 2.09]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_15.geometry}
              material={materials.chispas}
              position={[-0.649, -0.246, 0.163]}
              rotation={[-1.597, 0.026, 2.554]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_16.geometry}
              material={materials.chispas}
              position={[-0.475, -0.241, 0.47]}
              rotation={[-1.448, 0.31, 1.416]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_17.geometry}
              material={materials.chispas}
              position={[-0.451, -0.23, 0.608]}
              rotation={[1.519, 0.216, 1.498]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_18.geometry}
              material={materials.chispas}
              position={[-0.397, -0.24, 0.643]}
              rotation={[-1.688, -0.02, -3.007]}
              scale={[0.013, 0.023, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_19.geometry}
              material={materials.chispas}
              position={[-0.377, -0.243, 0.611]}
              rotation={[-1.63, -0.014, -2.969]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_20.geometry}
              material={materials.chispas}
              position={[0.094, -0.243, 0.742]}
              rotation={[-1.66, 0.058, 2.684]}
              scale={[0.015, 0.027, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_21.geometry}
              material={materials.chispas}
              position={[0.086, -0.229, 0.726]}
              rotation={[1.702, 0.154, 0.716]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_22.geometry}
              material={materials.chispas}
              position={[0.111, -0.25, 0.428]}
              rotation={[-1.573, -0.003, -2.386]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_23.geometry}
              material={materials.chispas}
              position={[0.098, -0.248, 0.584]}
              rotation={[-1.578, -0.004, -2.747]}
              scale={[0.018, 0.033, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_24.geometry}
              material={materials.chispas}
              position={[0.229, -0.25, 0.243]}
              rotation={[-1.572, 0, -2.855]}
              scale={[0.014, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_25.geometry}
              material={materials.chispas}
              position={[0.487, -0.248, 0.404]}
              rotation={[-1.585, -0.008, -2.763]}
              scale={[0.013, 0.024, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_26.geometry}
              material={materials.chispas}
              position={[0.392, -0.249, 0.372]}
              rotation={[-1.58, -0.002, -2.96]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_27.geometry}
              material={materials.chispas}
              position={[0.142, -0.25, 0.157]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_28.geometry}
              material={materials.chispas}
              position={[0.135, -0.25, 0.182]}
              rotation={[-1.571, 0, -2.761]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_29.geometry}
              material={materials.chispas}
              position={[0.133, -0.25, 0.214]}
              rotation={[-1.571, 0, -2.686]}
              scale={[0.015, 0.027, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_30.geometry}
              material={materials.chispas}
              position={[0.475, -0.248, 0.379]}
              rotation={[-1.578, -0.008, -2.511]}
              scale={[0.015, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_31.geometry}
              material={materials.chispas}
              position={[0.548, -0.247, 0.399]}
              rotation={[-1.573, -0.02, -2.061]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_32.geometry}
              material={materials.chispas}
              position={[0.134, -0.25, 0.092]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_33.geometry}
              material={materials.chispas}
              position={[0.188, -0.25, 0.099]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.013, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_34.geometry}
              material={materials.chispas}
              position={[0.224, -0.25, 0.075]}
              rotation={[-1.571, -0.001, -1.714]}
              scale={[0.013, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_35.geometry}
              material={materials.chispas}
              position={[0.384, -0.249, 0.108]}
              rotation={[-1.569, -0.005, -1.754]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_36.geometry}
              material={materials.chispas}
              position={[0.54, -0.248, 0.029]}
              rotation={[-1.579, -0.016, -2.331]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_37.geometry}
              material={materials.chispas}
              position={[0.618, -0.248, -0.036]}
              rotation={[-1.576, -0.02, -2.163]}
              scale={[0.013, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_38.geometry}
              material={materials.chispas}
              position={[0.513, -0.248, 0.097]}
              rotation={[-1.572, -0.021, -2.031]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_39.geometry}
              material={materials.chispas}
              position={[0.296, -0.25, -0.012]}
              rotation={[-1.571, -0.001, -1.512]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_40.geometry}
              material={materials.chispas}
              position={[0.659, -0.246, -0.043]}
              rotation={[-1.582, -0.035, -2.2]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_41.geometry}
              material={materials.chispas}
              position={[0.45, -0.25, -0.085]}
              rotation={[-1.572, -0.003, -1.337]}
              scale={[0.015, 0.028, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_42.geometry}
              material={materials.chispas}
              position={[0.601, -0.248, -0.103]}
              rotation={[-1.57, -0.011, -1.126]}
              scale={[0.013, 0.023, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_43.geometry}
              material={materials.chispas}
              position={[0.411, -0.25, -0.067]}
              rotation={[-1.572, -0.002, -1.435]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_44.geometry}
              material={materials.chispas}
              position={[0.424, -0.248, -0.334]}
              rotation={[-1.581, -0.023, -1.453]}
              scale={[0.018, 0.033, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_45.geometry}
              material={materials.chispas}
              position={[0.243, -0.25, -0.229]}
              rotation={[-1.571, -0.001, -1.285]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_46.geometry}
              material={materials.chispas}
              position={[0.289, -0.25, -0.332]}
              rotation={[-1.57, -0.002, -0.804]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_47.geometry}
              material={materials.chispas}
              position={[0.324, -0.249, -0.276]}
              rotation={[-1.574, -0.005, -1.569]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_48.geometry}
              material={materials.chispas}
              position={[0.374, -0.249, -0.368]}
              rotation={[-1.578, -0.011, -1.529]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_49.geometry}
              material={materials.chispas}
              position={[0.443, -0.247, -0.328]}
              rotation={[-1.579, -0.031, -1.359]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_50.geometry}
              material={materials.chispas}
              position={[0.164, -0.25, -0.164]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.015, 0.028, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_51.geometry}
              material={materials.chispas}
              position={[0.221, -0.25, -0.17]}
              rotation={[-1.571, -0.001, -1.367]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_52.geometry}
              material={materials.chispas}
              position={[0.268, -0.249, -0.427]}
              rotation={[-1.566, -0.001, -0.14]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_53.geometry}
              material={materials.chispas}
              position={[0.154, -0.25, -0.258]}
              rotation={[-1.57, 0, -0.394]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_54.geometry}
              material={materials.chispas}
              position={[0.099, -0.25, -0.188]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.016, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_55.geometry}
              material={materials.chispas}
              position={[0.128, -0.25, -0.2]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.018, 0.033, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_56.geometry}
              material={materials.chispas}
              position={[0.108, -0.249, -0.384]}
              rotation={[-1.566, -0.001, -0.187]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_57.geometry}
              material={materials.chispas}
              position={[0.029, -0.248, -0.54]}
              rotation={[-1.561, -0.016, -0.771]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_58.geometry}
              material={materials.chispas}
              position={[-0.001, -0.25, -0.136]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_59.geometry}
              material={materials.chispas}
              position={[0.031, -0.25, -0.153]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_60.geometry}
              material={materials.chispas}
              position={[0.011, -0.25, -0.211]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.015, 0.028, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_61.geometry}
              material={materials.chispas}
              position={[0.055, -0.25, -0.293]}
              rotation={[-1.57, -0.001, -0.496]}
              scale={[0.015, 0.028, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_62.geometry}
              material={materials.chispas}
              position={[0.091, -0.25, -0.368]}
              rotation={[-1.567, -0.002, -0.331]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_63.geometry}
              material={materials.chispas}
              position={[-0.102, -0.249, -0.473]}
              rotation={[-1.568, 0.002, 0.472]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_64.geometry}
              material={materials.chispas}
              position={[-0.121, -0.249, -0.548]}
              rotation={[-1.566, 0.008, 0.742]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_65.geometry}
              material={materials.chispas}
              position={[-0.133, -0.25, -0.361]}
              rotation={[-1.57, 0.003, 1.01]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_66.geometry}
              material={materials.chispas}
              position={[-0.114, -0.247, -0.652]}
              rotation={[-1.558, 0.011, 0.528]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_67.geometry}
              material={materials.chispas}
              position={[-0.243, -0.248, -0.453]}
              rotation={[-1.56, 0.014, 0.696]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_68.geometry}
              material={materials.chispas}
              position={[-0.164, -0.25, -0.164]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_69.geometry}
              material={materials.chispas}
              position={[-0.198, -0.25, -0.276]}
              rotation={[-1.569, 0, 0.16]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_70.geometry}
              material={materials.chispas}
              position={[-0.252, -0.25, -0.127]}
              rotation={[-1.571, 0.001, 1.509]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_71.geometry}
              material={materials.chispas}
              position={[-0.258, -0.25, -0.154]}
              rotation={[-1.571, 0.001, 1.177]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_72.geometry}
              material={materials.chispas}
              position={[-0.339, -0.25, -0.164]}
              rotation={[-1.57, 0.003, 1.784]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_73.geometry}
              material={materials.chispas}
              position={[-0.513, -0.248, -0.268]}
              rotation={[-1.565, 0.022, 1.81]}
              scale={[0.015, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_74.geometry}
              material={materials.chispas}
              position={[-0.134, -0.25, -0.092]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_75.geometry}
              material={materials.chispas}
              position={[-0.188, -0.25, -0.099]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.016, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_76.geometry}
              material={materials.chispas}
              position={[-0.469, -0.249, -0.071]}
              rotation={[-1.568, 0.011, 0.952]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_77.geometry}
              material={materials.chispas}
              position={[-0.564, -0.248, -0.032]}
              rotation={[-1.56, 0.023, 0.837]}
              scale={[0.015, 0.027, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_78.geometry}
              material={materials.chispas}
              position={[-0.566, -0.248, -0.002]}
              rotation={[-1.563, 0.017, 0.836]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_79.geometry}
              material={materials.chispas}
              position={[-0.136, -0.25, 0.001]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_80.geometry}
              material={materials.chispas}
              position={[-0.246, -0.25, -0.058]}
              rotation={[-1.571, 0.001, 1.241]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_81.geometry}
              material={materials.chispas}
              position={[-0.336, -0.25, -0.055]}
              rotation={[-1.57, 0.002, 0.946]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_82.geometry}
              material={materials.chispas}
              position={[-0.597, -0.248, 0.132]}
              rotation={[-1.579, 0.013, 2.397]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_83.geometry}
              material={materials.chispas}
              position={[-0.361, -0.25, 0.133]}
              rotation={[-1.573, 0.002, 2.579]}
              scale={[0.016, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_84.geometry}
              material={materials.chispas}
              position={[-0.433, -0.249, 0.139]}
              rotation={[-1.575, 0.004, 2.63]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_85.geometry}
              material={materials.chispas}
              position={[-0.517, -0.248, 0.193]}
              rotation={[-1.586, 0.014, 2.582]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_86.geometry}
              material={materials.chispas}
              position={[-0.578, -0.248, 0.164]}
              rotation={[-1.587, 0.015, 2.584]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_87.geometry}
              material={materials.chispas}
              position={[-0.472, -0.249, 0.082]}
              rotation={[-1.57, 0.004, 1.771]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_88.geometry}
              material={materials.chispas}
              position={[-0.64, -0.247, 0.144]}
              rotation={[-1.586, 0.02, 2.457]}
              scale={[0.013, 0.023, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_89.geometry}
              material={materials.chispas}
              position={[-0.52, -0.247, 0.209]}
              rotation={[-1.588, 0.018, 2.545]}
              scale={[0.011, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_90.geometry}
              material={materials.chispas}
              position={[-0.362, -0.249, 0.174]}
              rotation={[-1.574, 0.004, 2.421]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_91.geometry}
              material={materials.chispas}
              position={[-0.415, -0.248, 0.305]}
              rotation={[-1.565, 0.019, 1.761]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_92.geometry}
              material={materials.chispas}
              position={[-0.399, -0.248, 0.271]}
              rotation={[-1.568, 0.013, 1.854]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_93.geometry}
              material={materials.chispas}
              position={[-0.221, -0.25, 0.17]}
              rotation={[-1.57, 0.001, 1.775]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_94.geometry}
              material={materials.chispas}
              position={[-0.135, -0.25, 0.307]}
              rotation={[-1.573, 0, -2.995]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_95.geometry}
              material={materials.chispas}
              position={[-0.161, -0.25, 0.35]}
              rotation={[-1.574, -0.001, -2.918]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_96.geometry}
              material={materials.chispas}
              position={[-0.195, -0.248, 0.474]}
              rotation={[-1.585, -0.004, -2.955]}
              scale={[0.015, 0.028, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_97.geometry}
              material={materials.chispas}
              position={[-0.178, -0.249, 0.455]}
              rotation={[-1.582, -0.002, -2.994]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_98.geometry}
              material={materials.chispas}
              position={[-0.196, -0.249, 0.441]}
              rotation={[-1.58, -0.003, -2.895]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_99.geometry}
              material={materials.chispas}
              position={[-0.275, -0.249, 0.392]}
              rotation={[-1.573, 0.002, 2.557]}
              scale={[0.018, 0.033, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_100.geometry}
              material={materials.chispas}
              position={[-0.377, -0.247, 0.554]}
              rotation={[-1.592, 0.003, 3.031]}
              scale={[0.015, 0.027, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_101.geometry}
              material={materials.chispas}
              position={[-0.137, -0.247, 0.513]}
              rotation={[-1.592, 0.006, 2.944]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_102.geometry}
              material={materials.chispas}
              position={[-0.021, -0.249, 0.463]}
              rotation={[-1.574, 0.006, 2.341]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_103.geometry}
              material={materials.chispas}
              position={[-0.118, -0.247, 0.527]}
              rotation={[-1.594, 0.011, 2.805]}
              scale={[0.015, 0.028, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_104.geometry}
              material={materials.chispas}
              position={[-0.031, -0.25, 0.153]}
              rotation={[-1.571, 0, -1.571]}
              scale={[0.015, 0.027, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_105.geometry}
              material={materials.chispas}
              position={[0.012, -0.25, 0.296]}
              rotation={[-1.571, 0, -3.083]}
              scale={[0.017, 0.031, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_106.geometry}
              material={materials.chispas}
              position={[0.051, -0.25, 0.431]}
              rotation={[-1.573, 0, -3.017]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_107.geometry}
              material={materials.chispas}
              position={[-0.058, -0.25, 0.246]}
              rotation={[-1.571, 0, 2.812]}
              scale={[0.013, 0.023, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_108.geometry}
              material={materials.chispas}
              position={[-0.055, -0.25, 0.336]}
              rotation={[-1.572, 0.002, 2.515]}
              scale={[0.018, 0.032, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_109.geometry}
              material={materials.chispas}
              position={[0.067, -0.246, 0.674]}
              rotation={[-1.594, 0.017, 2.668]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_110.geometry}
              material={materials.chispas}
              position={[0.091, 0.219, -0.034]}
              rotation={[1.602, -0.364, -1.346]}
              scale={[0.012, 0.02, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_111.geometry}
              material={materials.chispas}
              position={[0.233, 0.11, 0.03]}
              rotation={[1.78, -0.288, -0.843]}
              scale={[0.018, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_112.geometry}
              material={materials.chispas}
              position={[0.246, 0.046, 0.158]}
              rotation={[1.764, -0.387, -1.029]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_113.geometry}
              material={materials.chispas}
              position={[0.301, 0.026, 0.16]}
              rotation={[1.838, -0.157, -0.459]}
              scale={[0.018, 0.032, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_114.geometry}
              material={materials.chispas}
              position={[0.285, -0.02, 0.259]}
              rotation={[1.858, -0.123, -0.348]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_115.geometry}
              material={materials.chispas}
              position={[0.265, -0.034, 0.293]}
              rotation={[1.873, -0.147, -0.395]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_116.geometry}
              material={materials.chispas}
              position={[0.227, -0.069, 0.367]}
              rotation={[1.907, -0.142, -0.351]}
              scale={[0.013, 0.023, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_117.geometry}
              material={materials.chispas}
              position={[0.226, -0.074, 0.375]}
              rotation={[1.902, -0.117, -0.296]}
              scale={[0.018, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_118.geometry}
              material={materials.chispas}
              position={[0.356, -0.091, 0.415]}
              rotation={[1.796, 0.018, 0.066]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_119.geometry}
              material={materials.chispas}
              position={[0.345, -0.117, 0.483]}
              rotation={[1.785, 0.032, 0.124]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_120.geometry}
              material={materials.chispas}
              position={[0.156, -0.128, 0.477]}
              rotation={[1.909, -0.024, -0.061]}
              scale={[0.014, 0.025, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_121.geometry}
              material={materials.chispas}
              position={[0.065, -0.183, 0.571]}
              rotation={[1.854, 0.088, 0.259]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_122.geometry}
              material={materials.chispas}
              position={[0.213, -0.191, 0.668]}
              rotation={[1.739, 0.102, 0.451]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_123.geometry}
              material={materials.chispas}
              position={[0.039, -0.187, 0.571]}
              rotation={[1.89, 0.075, 0.198]}
              scale={[0.018, 0.032, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_124.geometry}
              material={materials.chispas}
              position={[0.278, -0.18, 0.653]}
              rotation={[1.848, -0.08, -0.239]}
              scale={[0.016, 0.029, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_125.geometry}
              material={materials.chispas}
              position={[0.144, -0.206, 0.681]}
              rotation={[1.716, 0.134, 0.615]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_126.geometry}
              material={materials.chispas}
              position={[0.221, 0.066, 0.193]}
              rotation={[1.444, -1.027, -1.987]}
              scale={[0.012, 0.013, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_127.geometry}
              material={materials.chispas}
              position={[0.221, 0.058, 0.241]}
              rotation={[2.359, -1.516, -0.808]}
              scale={[0.016, 0.012, 0.016]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_128.geometry}
              material={materials.chispas}
              position={[0.145, -0.09, 0.436]}
              rotation={[2.208, -0.513, -0.662]}
              scale={[0.017, 0.024, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_129.geometry}
              material={materials.chispas}
              position={[-0.038, -0.184, 0.57]}
              rotation={[2.427, -0.218, -0.22]}
              scale={[0.013, 0.017, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_130.geometry}
              material={materials.chispas}
              position={[0.093, 0.221, 0.034]}
              rotation={[1.847, -0.173, -0.487]}
              scale={[0.018, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_131.geometry}
              material={materials.chispas}
              position={[0.141, 0.11, 0.187]}
              rotation={[1.923, 0.003, 0.007]}
              scale={[0.017, 0.029, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_132.geometry}
              material={materials.chispas}
              position={[0.091, 0.015, 0.345]}
              rotation={[1.835, 0.146, 0.436]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_133.geometry}
              material={materials.chispas}
              position={[0.123, 0.016, 0.358]}
              rotation={[1.81, 0.149, 0.476]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_134.geometry}
              material={materials.chispas}
              position={[0.13, 0.035, 0.319]}
              rotation={[1.838, 0.13, 0.39]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_135.geometry}
              material={materials.chispas}
              position={[0.035, 0.009, 0.337]}
              rotation={[1.934, 0.071, 0.168]}
              scale={[0.013, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_136.geometry}
              material={materials.chispas}
              position={[0.014, 0.004, 0.342]}
              rotation={[1.995, 0.019, 0.04]}
              scale={[0.011, 0.02, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_137.geometry}
              material={materials.chispas}
              position={[0.164, 0.011, 0.386]}
              rotation={[1.839, 0.038, 0.118]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_138.geometry}
              material={materials.chispas}
              position={[0.112, -0.029, 0.468]}
              rotation={[1.818, 0.08, 0.263]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_139.geometry}
              material={materials.chispas}
              position={[-0.073, -0.076, 0.455]}
              rotation={[1.743, 0.224, 0.79]}
              scale={[0.013, 0.023, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_140.geometry}
              material={materials.chispas}
              position={[-0.109, -0.087, 0.452]}
              rotation={[1.759, 0.231, 0.769]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_141.geometry}
              material={materials.chispas}
              position={[-0.092, -0.101, 0.52]}
              rotation={[1.658, 0.226, 1.017]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_142.geometry}
              material={materials.chispas}
              position={[-0.023, -0.091, 0.565]}
              rotation={[1.723, 0.174, 0.717]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_143.geometry}
              material={materials.chispas}
              position={[-0.055, -0.084, 0.5]}
              rotation={[1.684, 0.222, 0.933]}
              scale={[0.013, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_144.geometry}
              material={materials.chispas}
              position={[-0.145, -0.122, 0.537]}
              rotation={[1.629, 0.229, 1.114]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_145.geometry}
              material={materials.chispas}
              position={[-0.191, -0.142, 0.562]}
              rotation={[1.602, 0.224, 1.201]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_146.geometry}
              material={materials.chispas}
              position={[-0.165, -0.14, 0.606]}
              rotation={[1.63, 0.207, 1.079]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_147.geometry}
              material={materials.chispas}
              position={[-0.143, -0.134, 0.604]}
              rotation={[1.642, 0.205, 1.034]}
              scale={[0.012, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_148.geometry}
              material={materials.chispas}
              position={[-0.28, -0.18, 0.637]}
              rotation={[1.617, 0.206, 1.122]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_149.geometry}
              material={materials.chispas}
              position={[-0.396, -0.209, 0.54]}
              rotation={[1.514, 0.213, 1.517]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_150.geometry}
              material={materials.chispas}
              position={[0.072, 0.188, 0.124]}
              rotation={[1.624, -0.713, -1.615]}
              scale={[0.014, 0.022, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_151.geometry}
              material={materials.chispas}
              position={[-0.013, 0.076, 0.323]}
              rotation={[2.235, -0.418, -0.535]}
              scale={[0.013, 0.018, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_152.geometry}
              material={materials.chispas}
              position={[-0.122, 0.017, 0.395]}
              rotation={[2.263, -0.116, -0.15]}
              scale={[0.015, 0.023, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_153.geometry}
              material={materials.chispas}
              position={[0.018, 0.033, 0.311]}
              rotation={[2.156, -0.259, -0.385]}
              scale={[0.017, 0.027, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_154.geometry}
              material={materials.chispas}
              position={[-0.123, -0.005, 0.394]}
              rotation={[-2.504, -0.429, -2.774]}
              scale={[0.016, 0.018, 0.014]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_155.geometry}
              material={materials.chispas}
              position={[-0.534, -0.209, 0.321]}
              rotation={[-2.435, 0.411, 2.746]}
              scale={[0.014, 0.017, 0.012]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_156.geometry}
              material={materials.chispas}
              position={[-0.03, 0.122, 0.208]}
              rotation={[1.838, 0.266, 0.702]}
              scale={[0.012, 0.02, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_157.geometry}
              material={materials.chispas}
              position={[-0.025, 0.111, 0.237]}
              rotation={[1.76, 0.297, 0.895]}
              scale={[0.012, 0.021, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_158.geometry}
              material={materials.chispas}
              position={[-0.06, 0.08, 0.279]}
              rotation={[1.687, 0.306, 1.07]}
              scale={[0.012, 0.021, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_159.geometry}
              material={materials.chispas}
              position={[-0.095, 0.051, 0.327]}
              rotation={[1.631, 0.292, 1.193]}
              scale={[0.017, 0.03, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_160.geometry}
              material={materials.chispas}
              position={[-0.088, 0.043, 0.365]}
              rotation={[1.829, 0.177, 0.523]}
              scale={[0.018, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_161.geometry}
              material={materials.chispas}
              position={[-0.165, 0.029, 0.278]}
              rotation={[1.672, 0.325, 1.132]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_162.geometry}
              material={materials.chispas}
              position={[-0.176, 0.03, 0.26]}
              rotation={[1.76, 0.33, 0.95]}
              scale={[0.013, 0.023, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_163.geometry}
              material={materials.chispas}
              position={[-0.131, 0.034, 0.329]}
              rotation={[1.598, 0.296, 1.291]}
              scale={[0.014, 0.025, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_164.geometry}
              material={materials.chispas}
              position={[-0.172, 0.011, 0.354]}
              rotation={[1.561, 0.282, 1.386]}
              scale={[0.013, 0.023, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_165.geometry}
              material={materials.chispas}
              position={[-0.368, -0.074, 0.406]}
              rotation={[1.569, 0.257, 1.343]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_166.geometry}
              material={materials.chispas}
              position={[-0.529, -0.136, 0.305]}
              rotation={[1.607, 0.222, 1.698]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_167.geometry}
              material={materials.chispas}
              position={[-0.594, -0.173, 0.185]}
              rotation={[1.543, 0.222, 1.931]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_168.geometry}
              material={materials.chispas}
              position={[-0.638, -0.184, 0.2]}
              rotation={[1.536, 0.205, 1.978]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_169.geometry}
              material={materials.chispas}
              position={[-0.595, -0.201, 0.023]}
              rotation={[1.581, 0.302, 1.738]}
              scale={[0.014, 0.026, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_170.geometry}
              material={materials.chispas}
              position={[-0.625, -0.179, 0.208]}
              rotation={[1.541, 0.208, 1.956]}
              scale={[0.011, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_171.geometry}
              material={materials.chispas}
              position={[-0.623, -0.214, 0.015]}
              rotation={[1.527, 0.257, 1.943]}
              scale={[0.018, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_172.geometry}
              material={materials.chispas}
              position={[-0.656, -0.213, 0.073]}
              rotation={[1.502, 0.208, 2.098]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_173.geometry}
              material={materials.chispas}
              position={[-0.049, 0.184, 0.147]}
              rotation={[2.223, -0.339, -0.449]}
              scale={[0.012, 0.018, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_174.geometry}
              material={materials.chispas}
              position={[-0.083, 0.113, 0.199]}
              rotation={[2.14, 0.044, 0.07]}
              scale={[0.015, 0.025, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_175.geometry}
              material={materials.chispas}
              position={[-0.103, 0.105, 0.205]}
              rotation={[2.231, 0.005, 0.007]}
              scale={[0.016, 0.026, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_176.geometry}
              material={materials.chispas}
              position={[-0.235, 0.074, 0.22]}
              rotation={[2.527, 0.11, 0.095]}
              scale={[0.018, 0.021, 0.016]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_177.geometry}
              material={materials.chispas}
              position={[-0.274, -0.015, 0.239]}
              rotation={[1.847, 0.392, 0.9]}
              scale={[0.016, 0.027, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_178.geometry}
              material={materials.chispas}
              position={[-0.624, -0.145, -0.089]}
              rotation={[-1.862, 0.563, 2.038]}
              scale={[0.014, 0.023, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_179.geometry}
              material={materials.chispas}
              position={[-0.586, -0.161, -0.061]}
              rotation={[-1.917, 0.625, 2.041]}
              scale={[0.014, 0.021, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_180.geometry}
              material={materials.chispas}
              position={[-0.669, -0.181, -0.237]}
              rotation={[2.434, 1.419, 0.762]}
              scale={[0.016, 0.013, 0.016]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_181.geometry}
              material={materials.chispas}
              position={[-0.608, -0.201, -0.149]}
              rotation={[-1.764, 0.736, 1.723]}
              scale={[0.013, 0.019, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_182.geometry}
              material={materials.chispas}
              position={[-0.604, -0.209, -0.151]}
              rotation={[-1.811, 0.902, 1.673]}
              scale={[0.012, 0.015, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_183.geometry}
              material={materials.chispas}
              position={[-0.654, -0.205, -0.256]}
              rotation={[-1.651, 0.476, 1.788]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_184.geometry}
              material={materials.chispas}
              position={[-0.046, 0.224, 0.063]}
              rotation={[1.755, 0.235, 0.787]}
              scale={[0.017, 0.03, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_185.geometry}
              material={materials.chispas}
              position={[-0.21, 0.098, 0.175]}
              rotation={[1.683, 0.317, 1.445]}
              scale={[0.015, 0.026, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_186.geometry}
              material={materials.chispas}
              position={[-0.216, 0.093, 0.105]}
              rotation={[1.494, 0.395, 1.633]}
              scale={[0.015, 0.026, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_187.geometry}
              material={materials.chispas}
              position={[-0.313, 0.028, 0.067]}
              rotation={[1.661, 0.355, 1.494]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_188.geometry}
              material={materials.chispas}
              position={[-0.33, 0.023, 0.097]}
              rotation={[1.56, 0.315, 1.788]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_189.geometry}
              material={materials.chispas}
              position={[-0.371, 0.006, 0.104]}
              rotation={[1.514, 0.282, 1.952]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_190.geometry}
              material={materials.chispas}
              position={[-0.377, -0.011, 0.044]}
              rotation={[1.52, 0.307, 1.904]}
              scale={[0.015, 0.026, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_191.geometry}
              material={materials.chispas}
              position={[-0.401, -0.012, 0.076]}
              rotation={[1.489, 0.267, 2.041]}
              scale={[0.012, 0.021, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_192.geometry}
              material={materials.chispas}
              position={[-0.525, -0.068, 0.022]}
              rotation={[1.468, 0.214, 2.192]}
              scale={[0.014, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_193.geometry}
              material={materials.chispas}
              position={[-0.532, -0.159, -0.257]}
              rotation={[1.372, 0.113, 2.71]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_194.geometry}
              material={materials.chispas}
              position={[-0.458, -0.2, -0.393]}
              rotation={[1.337, 0.123, 2.731]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_195.geometry}
              material={materials.chispas}
              position={[-0.535, -0.223, -0.439]}
              rotation={[1.373, 0.03, 3.016]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_196.geometry}
              material={materials.chispas}
              position={[-0.633, -0.216, -0.4]}
              rotation={[1.396, 0.092, 2.743]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_197.geometry}
              material={materials.chispas}
              position={[-0.392, -0.224, -0.474]}
              rotation={[1.286, 0.188, 2.631]}
              scale={[0.014, 0.025, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_198.geometry}
              material={materials.chispas}
              position={[-0.194, 0.125, 0.076]}
              rotation={[2.11, 0.451, 0.677]}
              scale={[0.014, 0.022, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_199.geometry}
              material={materials.chispas}
              position={[-0.279, 0.082, 0.029]}
              rotation={[2.524, 0.658, 0.512]}
              scale={[0.013, 0.013, 0.012]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_200.geometry}
              material={materials.chispas}
              position={[-0.411, -0.126, -0.29]}
              rotation={[1.461, 0.83, 1.532]}
              scale={[0.012, 0.016, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_201.geometry}
              material={materials.chispas}
              position={[-0.306, -0.187, -0.632]}
              rotation={[-1.428, 0.594, 1.363]}
              scale={[0.013, 0.021, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_202.geometry}
              material={materials.chispas}
              position={[-0.346, -0.186, -0.499]}
              rotation={[-1.404, 0.772, 1.486]}
              scale={[0.012, 0.017, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_203.geometry}
              material={materials.chispas}
              position={[-0.091, 0.217, 0.022]}
              rotation={[1.612, 0.377, 1.607]}
              scale={[0.012, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_204.geometry}
              material={materials.chispas}
              position={[-0.176, 0.161, 0.023]}
              rotation={[1.414, 0.35, 2.096]}
              scale={[0.013, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_205.geometry}
              material={materials.chispas}
              position={[-0.246, 0.091, -0.062]}
              rotation={[1.354, 0.28, 2.328]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_206.geometry}
              material={materials.chispas}
              position={[-0.32, 0.032, -0.139]}
              rotation={[1.311, 0.142, 2.712]}
              scale={[0.012, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_207.geometry}
              material={materials.chispas}
              position={[-0.325, 0.027, -0.148]}
              rotation={[1.311, 0.132, 2.739]}
              scale={[0.017, 0.03, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_208.geometry}
              material={materials.chispas}
              position={[-0.34, 0.016, -0.166]}
              rotation={[1.314, 0.114, 2.785]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_209.geometry}
              material={materials.chispas}
              position={[-0.358, 0.032, -0.122]}
              rotation={[1.348, 0.161, 2.606]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_210.geometry}
              material={materials.chispas}
              position={[-0.421, -0.026, -0.235]}
              rotation={[1.498, 0.396, 1.858]}
              scale={[0.015, 0.026, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_211.geometry}
              material={materials.chispas}
              position={[-0.283, -0.1, -0.428]}
              rotation={[1.327, -0.039, -3.008]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_212.geometry}
              material={materials.chispas}
              position={[-0.352, -0.111, -0.468]}
              rotation={[1.354, -0.026, -3.044]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_213.geometry}
              material={materials.chispas}
              position={[-0.33, -0.131, -0.521]}
              rotation={[1.364, -0.044, -2.969]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_214.geometry}
              material={materials.chispas}
              position={[-0.226, -0.142, -0.52]}
              rotation={[1.354, -0.086, -2.824]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_215.geometry}
              material={materials.chispas}
              position={[-0.138, -0.194, -0.635]}
              rotation={[1.407, -0.134, -2.571]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_216.geometry}
              material={materials.chispas}
              position={[-0.134, -0.181, -0.593]}
              rotation={[1.375, -0.123, -2.671]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_217.geometry}
              material={materials.chispas}
              position={[-0.042, -0.21, -0.627]}
              rotation={[1.377, -0.143, -2.605]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_218.geometry}
              material={materials.chispas}
              position={[-0.211, 0.02, -0.305]}
              rotation={[-1.175, 1.195, 1.328]}
              scale={[0.013, 0.011, 0.012]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_219.geometry}
              material={materials.chispas}
              position={[-0.216, 0.018, -0.282]}
              rotation={[0.648, 1.296, 2.423]}
              scale={[0.014, 0.011, 0.014]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_220.geometry}
              material={materials.chispas}
              position={[-0.231, -0.008, -0.273]}
              rotation={[1.279, 0.512, 2.1]}
              scale={[0.012, 0.02, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_221.geometry}
              material={materials.chispas}
              position={[-0.183, -0.027, -0.373]}
              rotation={[-0.794, 1.049, 0.87]}
              scale={[0.018, 0.016, 0.017]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_222.geometry}
              material={materials.chispas}
              position={[-0.084, 0.057, -0.269]}
              rotation={[1.189, 0.017, 3.103]}
              scale={[0.015, 0.027, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_223.geometry}
              material={materials.chispas}
              position={[-0.027, -0.049, -0.467]}
              rotation={[1.415, -0.201, -2.367]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_224.geometry}
              material={materials.chispas}
              position={[0.136, -0.087, -0.431]}
              rotation={[1.279, -0.216, -2.577]}
              scale={[0.012, 0.021, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_225.geometry}
              material={materials.chispas}
              position={[0.151, -0.107, -0.468]}
              rotation={[1.421, -0.245, -2.257]}
              scale={[0.012, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_226.geometry}
              material={materials.chispas}
              position={[0.097, -0.106, -0.537]}
              rotation={[1.491, -0.222, -2.106]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_227.geometry}
              material={materials.chispas}
              position={[0.205, -0.143, -0.545]}
              rotation={[1.54, -0.231, -1.931]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_228.geometry}
              material={materials.chispas}
              position={[0.21, -0.166, -0.66]}
              rotation={[1.148, -0.109, -2.918]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_229.geometry}
              material={materials.chispas}
              position={[0.267, -0.156, -0.494]}
              rotation={[1.518, -0.256, -1.972]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_230.geometry}
              material={materials.chispas}
              position={[0.362, -0.194, -0.504]}
              rotation={[1.592, -0.24, -1.745]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_231.geometry}
              material={materials.chispas}
              position={[0.308, -0.187, -0.627]}
              rotation={[1.566, -0.206, -1.861]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_232.geometry}
              material={materials.chispas}
              position={[0.331, -0.192, -0.607]}
              rotation={[1.591, -0.207, -1.765]}
              scale={[0.015, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_233.geometry}
              material={materials.chispas}
              position={[0.412, -0.2, -0.418]}
              rotation={[1.457, -0.328, -2.034]}
              scale={[0.018, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_234.geometry}
              material={materials.chispas}
              position={[0.366, -0.202, -0.589]}
              rotation={[1.614, -0.204, -1.676]}
              scale={[0.015, 0.027, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_235.geometry}
              material={materials.chispas}
              position={[0.296, -0.189, -0.66]}
              rotation={[1.355, -0.195, -2.507]}
              scale={[0.012, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_236.geometry}
              material={materials.chispas}
              position={[0.431, -0.224, -0.612]}
              rotation={[1.613, -0.197, -1.678]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_237.geometry}
              material={materials.chispas}
              position={[-0.039, 0.107, -0.26]}
              rotation={[0.827, 0.807, 2.335]}
              scale={[0.017, 0.018, 0.015]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_238.geometry}
              material={materials.chispas}
              position={[-0.023, 0.097, -0.283]}
              rotation={[0.805, 0.709, 2.422]}
              scale={[0.017, 0.019, 0.015]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_239.geometry}
              material={materials.chispas}
              position={[0.006, 0.077, -0.318]}
              rotation={[0.769, 0.57, 2.563]}
              scale={[0.017, 0.021, 0.015]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_240.geometry}
              material={materials.chispas}
              position={[0.137, -0.018, -0.397]}
              rotation={[-0.647, 0.389, 0.342]}
              scale={[0.011, 0.013, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_241.geometry}
              material={materials.chispas}
              position={[0.105, -0.034, -0.385]}
              rotation={[0.689, 0.165, 2.981]}
              scale={[0.014, 0.018, 0.012]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_242.geometry}
              material={materials.chispas}
              position={[0.255, -0.126, -0.424]}
              rotation={[1.118, -0.26, -2.662]}
              scale={[0.014, 0.024, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_243.geometry}
              material={materials.chispas}
              position={[0.529, -0.175, -0.346]}
              rotation={[-1.03, -0.135, -0.222]}
              scale={[0.013, 0.022, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_244.geometry}
              material={materials.chispas}
              position={[0.563, -0.195, -0.319]}
              rotation={[-1.028, -0.199, -0.322]}
              scale={[0.011, 0.019, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_245.geometry}
              material={materials.chispas}
              position={[0.498, -0.194, -0.343]}
              rotation={[-0.642, -0.367, -0.321]}
              scale={[0.016, 0.019, 0.014]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_246.geometry}
              material={materials.chispas}
              position={[0.388, -0.181, -0.403]}
              rotation={[1.232, -0.37, -2.362]}
              scale={[0.013, 0.022, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_247.geometry}
              material={materials.chispas}
              position={[0.106, 0.061, -0.271]}
              rotation={[1.441, -0.314, -2.091]}
              scale={[0.018, 0.032, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_248.geometry}
              material={materials.chispas}
              position={[0.136, 0.029, -0.343]}
              rotation={[1.55, -0.289, -1.841]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_249.geometry}
              material={materials.chispas}
              position={[0.218, 0, -0.287]}
              rotation={[1.536, -0.325, -1.844]}
              scale={[0.014, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_250.geometry}
              material={materials.chispas}
              position={[0.223, -0.011, -0.351]}
              rotation={[1.62, -0.276, -1.636]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_251.geometry}
              material={materials.chispas}
              position={[0.313, -0.051, -0.389]}
              rotation={[1.643, -0.244, -1.572]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_252.geometry}
              material={materials.chispas}
              position={[0.388, -0.083, -0.25]}
              rotation={[1.689, -0.284, -1.43]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_253.geometry}
              material={materials.chispas}
              position={[0.34, -0.061, -0.345]}
              rotation={[1.696, -0.236, -1.396]}
              scale={[0.013, 0.024, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_254.geometry}
              material={materials.chispas}
              position={[0.483, -0.117, -0.345]}
              rotation={[1.491, -0.219, -1.599]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_255.geometry}
              material={materials.chispas}
              position={[0.55, -0.151, -0.231]}
              rotation={[1.572, -0.23, -1.312]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_256.geometry}
              material={materials.chispas}
              position={[0.526, -0.156, -0.081]}
              rotation={[1.707, -0.408, -1.36]}
              scale={[0.017, 0.029, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_257.geometry}
              material={materials.chispas}
              position={[0.597, -0.185, -0.121]}
              rotation={[1.601, -0.238, -1.221]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_258.geometry}
              material={materials.chispas}
              position={[0.618, -0.184, -0.165]}
              rotation={[1.612, -0.214, -1.151]}
              scale={[0.017, 0.03, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_259.geometry}
              material={materials.chispas}
              position={[0.661, -0.216, -0.065]}
              rotation={[1.643, -0.206, -1.03]}
              scale={[0.012, 0.022, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_260.geometry}
              material={materials.chispas}
              position={[0.701, -0.206, -0.176]}
              rotation={[1.604, -0.197, -1.158]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_261.geometry}
              material={materials.chispas}
              position={[0.594, -0.205, 0.004]}
              rotation={[1.536, -0.333, -1.492]}
              scale={[0.017, 0.031, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_262.geometry}
              material={materials.chispas}
              position={[0.184, 0.097, -0.216]}
              rotation={[0.577, 0.042, 3.108]}
              scale={[0.013, 0.015, 0.012]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_263.geometry}
              material={materials.chispas}
              position={[0.106, 0.098, -0.21]}
              rotation={[0.977, -0.077, -3.026]}
              scale={[0.013, 0.021, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_264.geometry}
              material={materials.chispas}
              position={[0.274, 0.045, -0.218]}
              rotation={[-0.148, -0.107, -0.021]}
              scale={[0.016, 0.013, 0.016]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_265.geometry}
              material={materials.chispas}
              position={[0.213, 0.025, -0.237]}
              rotation={[1.09, -0.311, -2.605]}
              scale={[0.015, 0.025, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_266.geometry}
              material={materials.chispas}
              position={[0.368, -0.063, -0.204]}
              rotation={[1.37, -0.466, -2.018]}
              scale={[0.014, 0.023, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_267.geometry}
              material={materials.chispas}
              position={[0.58, -0.104, -0.009]}
              rotation={[-1.045, -0.627, -0.89]}
              scale={[0.015, 0.021, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_268.geometry}
              material={materials.chispas}
              position={[0.53, -0.127, -0.038]}
              rotation={[-0.88, -0.721, -0.804]}
              scale={[0.012, 0.014, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_269.geometry}
              material={materials.chispas}
              position={[0.46, -0.114, -0.139]}
              rotation={[1.505, -0.512, -1.726]}
              scale={[0.017, 0.029, 0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_270.geometry}
              material={materials.chispas}
              position={[0.536, -0.163, -0.05]}
              rotation={[1.676, -0.487, -1.393]}
              scale={[0.015, 0.025, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_271.geometry}
              material={materials.chispas}
              position={[0.634, -0.225, 0.263]}
              rotation={[-1.525, -0.525, -1.467]}
              scale={[0.012, 0.021, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_272.geometry}
              material={materials.chispas}
              position={[0.351, 0.017, -0.113]}
              rotation={[1.61, -0.293, -1.253]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_273.geometry}
              material={materials.chispas}
              position={[0.354, 0.027, -0.181]}
              rotation={[1.435, -0.266, -1.767]}
              scale={[0.017, 0.029, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_274.geometry}
              material={materials.chispas}
              position={[0.428, -0.011, -0.13]}
              rotation={[1.566, -0.266, -1.36]}
              scale={[0.016, 0.029, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_275.geometry}
              material={materials.chispas}
              position={[0.439, -0.051, 0.011]}
              rotation={[1.691, -0.253, -0.974]}
              scale={[0.014, 0.025, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_276.geometry}
              material={materials.chispas}
              position={[0.496, -0.05, -0.058]}
              rotation={[1.654, -0.229, -1.035]}
              scale={[0.015, 0.026, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_277.geometry}
              material={materials.chispas}
              position={[0.48, -0.076, 0.049]}
              rotation={[1.721, -0.211, -0.815]}
              scale={[0.012, 0.022, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_278.geometry}
              material={materials.chispas}
              position={[0.433, -0.09, 0.143]}
              rotation={[1.676, -0.35, -1.158]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_279.geometry}
              material={materials.chispas}
              position={[0.631, -0.131, 0.101]}
              rotation={[1.425, -0.41, -1.806]}
              scale={[0.015, 0.026, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_280.geometry}
              material={materials.chispas}
              position={[0.619, -0.142, 0.16]}
              rotation={[1.71, -0.167, -0.732]}
              scale={[0.014, 0.026, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_281.geometry}
              material={materials.chispas}
              position={[0.512, -0.152, 0.246]}
              rotation={[1.772, -0.135, -0.5]}
              scale={[0.012, 0.021, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_282.geometry}
              material={materials.chispas}
              position={[0.516, -0.166, 0.283]}
              rotation={[1.776, -0.114, -0.424]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_283.geometry}
              material={materials.chispas}
              position={[0.426, -0.213, 0.436]}
              rotation={[1.824, -0.143, -0.442]}
              scale={[0.016, 0.028, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_284.geometry}
              material={materials.chispas}
              position={[0.666, -0.215, 0.376]}
              rotation={[1.648, -0.419, -1.299]}
              scale={[0.014, 0.024, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_285.geometry}
              material={materials.chispas}
              position={[0.263, -0.24, 0.577]}
              rotation={[-1.613, -0.127, -2.146]}
              scale={[0.018, 0.032, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_286.geometry}
              material={materials.chispas}
              position={[0.279, -0.23, 0.59]}
              rotation={[-1.812, -0.56, -1.969]}
              scale={[0.014, 0.024, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_287.geometry}
              material={materials.chispas}
              position={[0.2, -0.244, 0.632]}
              rotation={[-1.581, -0.065, -2.059]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_288.geometry}
              material={materials.chispas}
              position={[0.175, -0.24, 0.729]}
              rotation={[-1.606, -0.107, -2.158]}
              scale={[0.014, 0.025, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_289.geometry}
              material={materials.chispas}
              position={[0.191, -0.233, 0.747]}
              rotation={[-1.782, -0.331, -2.231]}
              scale={[0.013, 0.023, 0.006]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_290.geometry}
              material={materials.chispas}
              position={[0.21, -0.246, 0.572]}
              rotation={[-1.579, -0.041, -2.105]}
              scale={[0.011, 0.02, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_291.geometry}
              material={materials.chispas}
              position={[0.322, -0.212, 0.53]}
              rotation={[-2.275, -0.911, -2.235]}
              scale={[0.012, 0.013, 0.012]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_292.geometry}
              material={materials.chispas}
              position={[0.299, -0.189, 0.642]}
              rotation={[-1.877, -0.679, -1.932]}
              scale={[0.011, 0.017, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_293.geometry}
              material={materials.chispas}
              position={[0.367, -0.157, 0.51]}
              rotation={[-1.475, -0.546, -1.38]}
              scale={[0.012, 0.02, 0.007]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_294.geometry}
              material={materials.chispas}
              position={[0.347, -0.176, 0.525]}
              rotation={[-1.531, -0.566, -1.476]}
              scale={[0.016, 0.026, 0.009]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_295.geometry}
              material={materials.chispas}
              position={[0.387, -0.141, 0.45]}
              rotation={[-1.414, -0.581, -1.235]}
              scale={[0.014, 0.023, 0.008]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_296.geometry}
              material={materials.chispas}
              position={[0.413, -0.056, 0.215]}
              rotation={[-1.428, -0.85, -1.573]}
              scale={[0.016, 0.022, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_297.geometry}
              material={materials.chispas}
              position={[0.369, 0, 0.075]}
              rotation={[0.173, -1.097, -2.954]}
              scale={[0.011, 0.009, 0.011]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_298.geometry}
              material={materials.chispas}
              position={[0.246, 0.118, -0.045]}
              rotation={[0.75, -0.523, -2.619]}
              scale={[0.016, 0.02, 0.014]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chispas_299.geometry}
              material={materials.chispas}
              position={[0.154, 0.143, -0.091]}
              rotation={[1.242, -0.416, -2.28]}
              scale={[0.014, 0.023, 0.008]}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.chispas_300.geometry}
            material={materials.chispas}
            position={[0, 1.305, 0]}
            scale={[0.047, 0.085, 0.047]}
          />
        </>
      )}
      {IscherryPearl && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cherry.geometry}
          material={materials["charrie texture"]}
          position={[0.013, 2.841, -0.07]}
          rotation={[-1.457, -1.34, -1.314]}
          scale={[17.419, 16.293, 17.379]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/cupcake2.gltf");

export default ({ flavor, isCreamFilling, IscherryPearl }) => {
  return (
    <>
      <Stage>
        <Cupcake2
          flavor={flavor}
          isCreamFilling={isCreamFilling}
          IscherryPearl={IscherryPearl}
        />
        <OrbitControls enableZoom={true} />
      </Stage>
    </>
  );
};
